language: csharp
solution: Source/GlassRoom/GlassRoom.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore Source/GlassRoom/GlassRoom.sln
after_script:
  #- nunit-console Tests/bin/Release/Tests.dll
  
# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:

